#spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.auto-index-creation=true
#error.handling.http-status-in-json-response=true
#error.handling.exception-logging=NO_LOGGING
#error.handling.full-stacktrace-http-statuses=5xx
#error.handling.log-levels.5xx=ERROR
#error.handling.codes.UserIdValid=USER_ID_VALID
#error.handling.codes.LeadIdValid=LEAD_ID_VALID
#springdoc.pathsToMatch=/, /api/**
#spring.main.lazy-initialization=false
#telegram.bot.token=${TELEGRAM_BOT_TOKEN}
#telegram.chat.id=${TELEGRAM_CHAT_ID}


# MongoDB Atlas
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

#  Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_gmail@gmail.com
spring.mail.password=your_16_digit_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Error Handling
error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR
error.handling.codes.UserIdValid=USER_ID_VALID
error.handling.codes.LeadIdValid=LEAD_ID_VALID

#  SpringDoc
springdoc.pathsToMatch=/, /api/**
spring.main.lazy-initialization=false

# Telegram
telegram.bot.token=8591288592:AAEVlUCUio1jNYe1Gr6-C0bTGtb8kVSfAQM
telegram.chat.id=1342143998
