#spring.application.name=leadflow-backend
#spring.mongodb.uri=${MONGO_URL}
#spring.data.mongodb.auto-index-creation=true
#
## JWT Configuration (Updated to match the error log)
#JWT_SECRET=${JWT_SECRET_TOKEN}
#JWT_EXPIRATION=${JWT_EXPIRATION}
#
## Telegram & Mail
#telegram.bot.token=${TELEGRAM_BOT_TOKEN}
#telegram.chat.id=${TELEGRAM_CHAT_ID}
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## Server & Other configs
#frontend.url=${FRONTEND_URL}
#spring.main.lazy-initialization=false

#spring.application.name=leadflow-backend
#spring.mongodb.uri=mongodb+srv://admin:ishika@cluster0.rfly8xf.mongodb.net/leadflow_db
##spring.data.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.auto-index-creation=true
#error.handling.http-status-in-json-response=true
#error.handling.exception-logging=NO_LOGGING
#error.handling.full-stacktrace-http-statuses=5xx
#error.handling.log-levels.5xx=ERROR
#error.handling.codes.UserIdValid=USER_ID_VALID
#error.handling.codes.LeadIdValid=LEAD_ID_VALID
#springdoc.pathsToMatch=/, /api/**
#spring.main.lazy-initialization=false
#telegram.bot.token=8591288592:AAEVlUCUio1jNYe1Gr6-C0bTGtb8kVSfAQM
#telegram.chat.id=1342143998
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=ishikakag09@gmail.com
#spring.mail.password=hcda vywv fjtj xwwz
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#server.port=8080
#jwt.secret.token=leadflowBackendJwtAuthenticationSecretKey2026UltraSecureVeryLongSecretKeyForHS512AlgorithmProductionReady
#jwt.secret=supersecret123
#jwt.expiration=604800000
#frontend.url=http://localhost:3000
##MAIL_USERNAME=ishikakag09@gmail.com
##MAIL_PASSWORD=hcda vywv fjtj xwwz
##JWT_SECRET_TOKEN=leadflowBackendJwtAuthenticationSecretKey2026UltraSecureVeryLongSecretKeyForHS512AlgorithmProductionReady
##JWT_EXPIRATION=604800000
spring.application.name=leadflow-backend
spring.mongodb.uri=mongodb+srv://admin:ishika@cluster0.rfly8xf.mongodb.net/leadflow_db
spring.data.mongodb.auto-index-creation=true

# JWT Configuration (Updated to match the error log)
JWT_SECRET=leadflowBackendJwtAuthenticationSecretKey2026UltraSecureVeryLong
jwt.secret=leadflowBackendJwtAuthenticationSecretKey2026UltraSecureVeryLong
jwt.expiration=604800000
JWT_EXPIRATION=604800000

# Telegram & Mail
telegram.bot.token=8591288592:AAEVlUCUio1jNYe1Gr6-C0bTGtb8kVSfAQM
telegram.chat.id=1342143998
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ishikakag09@gmail.com
spring.mail.password=hcda vywv fjtj xwwz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server & Other configs
server.port=8080
frontend.url=http://localhost:3000
spring.main.lazy-initialization=false
