spring.application.name=leadflow-backend
spring.data.mongodb.uri=mongodb+srv://admin:ishika@cluster0.rfly8xf.mongodb.net/leadflow_db
error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR
error.handling.codes.UserIdValid=USER_ID_VALID
error.handling.codes.LeadIdValid=LEAD_ID_VALID
springdoc.pathsToMatch=/,/api/**
spring.main.lazy-initialization=false
server.port=8080

spring.data.mongodb.auto-index-creation=true
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION=${JWT_EXPIRATION}

